Controllers/BuyFController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using QuanLyCayXanh.Models;
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyCayXanh.Controllers
{
    public class BuyFController : Controller
    {
        QuanLyCayXanhEntities db = new QuanLyCayXanhEntities   ();

        public ActionResult Index()
        {
            if (Session["TaiKhoan"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View(db.BuyFs.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.FertilizerID = new SelectList(db.Fertilizers.ToList().OrderBy(n => n.Name), "FertilizerID", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            // kiểm tra ,thông báo lỗi
            if (string.IsNullOrWhiteSpace(f["FertilizerID"]))
            {
                ModelState.AddModelError("FertilizerID", "Không được để trống.");
            }
            if (string.IsNullOrWhiteSpace(f["Provider"]))
            {
                ModelState.AddModelError("Provider", "Không được để trống.");
            }
            if (string.IsNullOrWhiteSpace(f["Quantity"]))
            {
                ModelState.AddModelError("Quantity", "Không được để trống.");
            }
            if (string.IsNullOrWhiteSpace(f["Price"]))
            {
                ModelState.AddModelError("Price", "Không được để trống.");
            }
            if (string.IsNullOrWhiteSpace(f["Date"]))
            {
                ModelState.AddModelError("Date", "Không được để trống.");
            }

            if (!ModelState.IsValid)
            {
                ViewBag.FertilizerID = new SelectList(db.Fertilizers.ToList().OrderBy(n => n.Name), "FertilizerID", "Name");
                return View();
            }

            BuyF buy = new BuyF(); // gán giá trị
            buy.FertilizerID = int.Parse(f["FertilizerID"]);
            buy.Provider = f["Provider"];
            buy.Quantity = int.Parse(f["Quantity"]);
            buy.Price = int.Parse(f["Price"]);

            /*int DateY;
            if (int.TryParse(f["Date"], out DateY))
            {
                buy.Date = new DateTime(DateY, 1, 1); // Lấy năm và đặt tháng và ngày là mặc định (1/1)
            }
            else
            {
                ModelState.AddModelError("Date", "Invalid date format.");
                ViewBag.FertilizerID = new SelectList(db.Fertilizers.ToList().OrderBy(n => n.Name), "FertilizerID", "Name");
                return View();
            }*/

            DateTime dateValue;
            if (DateTime.TryParseExact(f["Date"], "yyyy-MM-dd", null, System.Globalization.DateTimeStyles.None, out dateValue))
            {
                buy.Date = dateValue;
            }
            else
            {
                ModelState.AddModelError("Date", "Định dạng ngày không hợp lệ (định dạng phải là yyyy-MM-dd).");
                ViewBag.FertilizerID = new SelectList(db.Fertilizers.ToList().OrderBy(n => n.Name), "FertilizerID", "Name");
                return View();
            }
            /* if (fFileUpload != null)
             {
                 var sFileName = Path.GetFileName(fFileUpload.FileName);
                 var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                 if (!System.IO.File.Exists(path))
                 {
                     fFileUpload.SaveAs(path);
                 }
                 buy.Image = sFileName;
             }*/
            //   Thêm đối tượng buy vào cơ sở dữ liệu và lưu thay đổithêm buy vào csld thay dổi
            db.BuyFs.Add(buy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        public ActionResult Edit(int id)
        { // hiển thị from chỉnh sửa
            var buy = db.BuyFs.SingleOrDefault(n => n.BuyFID == id);
            if (buy == null)
            {
                return HttpNotFound();
            }

            ViewBag.FertilizerID = new SelectList(db.Fertilizers.ToList().OrderBy(n => n.Name), "FertilizerID", "Name", buy.FertilizerID);// sắp xếp 
            return View(buy);
        }

        [HttpPost] // xử lí from 
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, BuyF buy, HttpPostedFileBase fFileUpload)
        {
            var existingBuy = db.BuyFs.SingleOrDefault(n => n.BuyFID == id);
            if (existingBuy == null)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid) // kiểm tra dữ liệu
            {
                try
                {
                    // Cập nhật các thuộc tính của existingBuy từ mô hình buy
                    existingBuy.FertilizerID = buy.FertilizerID;
                    existingBuy.Provider = buy.Provider;
                    existingBuy.Quantity = buy.Quantity;
                    existingBuy.Date = buy.Date;
                    existingBuy.Price = buy.Price;

                    // Cập nhật vào cơ sở dữ liệu
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // Xử lý lỗi
                    ModelState.AddModelError("", "Có lỗi xảy ra khi lưu dữ liệu. Vui lòng thử lại.");
                }
            }

            // Nếu ModelState không hợp lệ, load lại dropdown và hiển thị lại form với thông báo lỗi
            ViewBag.FertilizerID = new SelectList(db.Fertilizers.ToList().OrderBy(n => n.Name), "FertilizerID", "Name", existingBuy.FertilizerID);
            return View(existingBuy);
        }


        // GET: Hiển thị chi tiết đối tượng BuyF

        public ActionResult Details(int id)
        {
            var buyf = db.BuyFs.SingleOrDefault(n => n.BuyFID == id);
            if (buyf == null)
            {
                return HttpNotFound();
            }
            return View(buyf);
        }
        // GET: Hiển thị form xóa đối tượng BuyF
        public ActionResult Delete(int id)
        {
            var buyf = db.BuyFs.SingleOrDefault(n => n.BuyFID == id);
            if (buyf == null)
            {
                return HttpNotFound();
            }
            return View(buyf);
        }
        // POST: Xác nhận xóa đối tượng BuyF
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var buyf = db.BuyFs.SingleOrDefault(n => n.BuyFID == id);
            if (buyf == null)
            {
                return HttpNotFound();
            }
            db.BuyFs.Remove(buyf); // Xóa đối tượng khỏi cơ sở dữ liệu
            db.SaveChanges(); // Lưu thay đổi vào cơ sở dữ liệu
            return RedirectToAction("Index"); // Chuyển hướng về trang Index
        }

        // GET: BuyF/ExportToPdf
        public ActionResult ExportToPdf()
        {
            var buyfs = db.BuyFs.ToList(); // đọc dữ liệu

            // Tính toán các số liệu thống kê
            int totalCount = buyfs.Count();
            int totalQuantity = buyfs.Sum(b => b.Quantity);
            decimal totalPrice = buyfs.Sum(b => b.Quantity * b.Price); // Tính tổng giá trị phân bón

            // Truyền dữ liệu thống kê đến view thông qua ViewBag
            ViewBag.TotalCount = totalCount;
            ViewBag.TotalQuantity = totalQuantity;
            ViewBag.TotalPrice = totalPrice; // Truyền tổng giá trị đến view

            return View(buyfs);
        }



        // POST: BuyF/GeneratePdf
        [HttpPost]
        public ActionResult GeneratePdf()
        {
            var buyfs = db.BuyFs.ToList(); // đọc dữ liệu

            // tính toán dữ liệu 
            int totalCount = buyfs.Count();
            int totalQuantity = buyfs.Sum(b => b.Quantity);
            decimal totalPrice = buyfs.Sum(b => b.Quantity * b.Price);

            // Tạo MemoryStream để lưu trữ PDF
            MemoryStream workStream = new MemoryStream();
            Document document = new Document(PageSize.A4, 25, 25, 30, 30);
            PdfWriter.GetInstance(document, workStream).CloseStream = false;

            // mở tài  liệu
            document.Open();

            // thiết lập múi giờ vn
            TimeZoneInfo vietnamTimeZone = TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time");
            DateTime vietnamTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, vietnamTimeZone);

            // thêm tiêu đề 
            string title = "Báo Cáo Cây Xanh";
            string reportDate = vietnamTime.ToString("dd/MM/yyyy");

            // Đường dẫn tương đối đến font
            string fontPath = Server.MapPath("~/Fonts/times.ttf");

            // Tạo BaseFont từ font đã cài đặt
            BaseFont baseFont = BaseFont.CreateFont(fontPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);

            // Create a Font using the created BaseFont
            Font font = new Font(baseFont, 12, Font.NORMAL);

            //  Thêm tiêu đề và ngày báo cáo vào tài liệu

            document.Add(new Paragraph(title, font));
            document.Add(new Paragraph("Ngày xuất báo cáo: " + reportDate, font));

            // Thêm các số liệu thống kê
            document.Add(new Paragraph("\n"));
            document.Add(new Paragraph("Tổng số lần mua: " + totalCount, font));
            document.Add(new Paragraph("Tổng số lượng phân bón: " + totalQuantity, font));
            document.Add(new Paragraph("Tổng giá trị phân bón: " + totalPrice.ToString("N0") + " ₫", font)); // Thay đổi định dạng số để thêm ký hiệu đồng

            document.Add(new Paragraph("\n"));

            // Tạo bảng với 5 cột  // Add table
            PdfPTable table = new PdfPTable(5); // 5 columns as per your requirement

            //// Thiết lập tỷ lệ chiều rộng của bảng

Controllers/RolesController.cs
using QuanLyCayXanh.Models;
using System;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web.Mvc;

namespace QuanLyCayXanh.Controllers
{
    public class RolesController : Controller
    {
        // GET: Roles
        QuanLyCayXanhEntities db = new QuanLyCayXanhEntities();

        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.RoleID = new SelectList(db.Roledetails.OrderBy(n => n.Name), "IDRoles", "Name");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(User user, FormCollection f)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Gán Role từ dropdownlist vào user.Role
                    user.Role = int.Parse(f["RoleID"]);

                    // Thêm user vào db và lưu thay đổi
                    db.Users.Add(user);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var validationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        ModelState.AddModelError(validationError.PropertyName, validationError.ErrorMessage);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error creating user: " + ex.Message);
            }

            // Nếu có lỗi, cần phải load lại dropdownlist RoleID với các giá trị đã chọn
            ViewBag.RoleID = new SelectList(db.Roledetails.OrderBy(n => n.Name), "IDRoles", "Name", user.Role);
            return View(user);
        }


        public ActionResult Edit(int id)
        {
            ViewBag.RoleID = new SelectList(db.Roledetails.ToList().OrderBy(n => n.Name), "IDRoles", "Name");
            var roles = db.Users.SingleOrDefault(n => n.IDuser == id);
            if (roles == null)
            {
                return HttpNotFound();
            }
            return View(roles);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, FormCollection f)
        {
            var Role = db.Users.SingleOrDefault(n => n.IDuser == id);
            if (Role == null)
            {
                return HttpNotFound();
            }
            Role.Role = int.Parse(f["RoleID"]);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /*  public ActionResult Details(int id)
          {
              var roles = db.User.SingleOrDefault(n => n.IDuser == id);
              if (roles == null)
              {
                  return HttpNotFound();
              }
              return View(roles);
          }*/
        public ActionResult Details(int id)
        {
            var user = db.Users.SingleOrDefault(n => n.IDuser == id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        public ActionResult Delete(int id)
        {
            var roles = db.Users.SingleOrDefault(n => n.IDuser == id);
            if (roles == null)
            {
                return HttpNotFound();
            }
            return View(roles);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var roles = db.Users.SingleOrDefault(n => n.IDuser == id);
            if (roles == null)
            {
                return HttpNotFound();
            }
            db.Users.Remove(roles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




    }
}

Views/Shared/_Layout.cshtml
@using QuanLyCayXanh.Models;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NHÓM 3</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            background-color: #f8f9fa;
            color: #343a40;
        }

        footer {
            background-color: #FF99CC;
            color: #ffffff;
            padding: 10px 0;
            text-align: center;
            position: fixed;
            bottom: 0;
            width: 100%;
        }

        .navbar-brand {
            font-size: 1.5rem;
            font-weight: bold;
            color: #ffffff;
        }

        .navbar-nav li a {
            color: #ffffff !important;
        }

        .body-content {
            margin-top: 20px;
            margin-bottom: 60px; /* Adjust margin to prevent overlap with footer */
        }

        footer p {
            background-color: #000022; /* Màu chữ dưới  */
            display: inline-block;
            padding: 5px 10px;
            border-radius: 5px;
        }

            footer p::before {
                content: "";
                display: block;
                width: 100%;
                height: 100%;
                position: absolute;
                top: 0;
                left: 0;
                z-index: -1;
                background-color: #000022; /* Màu nền xanh lá cây đậm */
                border-radius: 5px;
            }
   </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #000022; ">
        <div class="container">
            @Html.ActionLink("Quản Lý ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    @{
                        User ac = (User)Session["TaiKhoan"];
                        if (ac != null)
                        {
                            if (ac.Role == 0)
                            {
                                <li class="nav-item">@Html.ActionLink("Quản lý cây xanh", "Index", "Greenery", null, new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Quản lý mua cây xanh", "Index", "Purchase", null, new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Quản lý phân bón cây xanh", "Index", "Fertilizer", null, new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Quản lý mua phân bón ", "Index", "BuyF", null, new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Phân Quyền", "Index", "Roles", null, new { @class = "nav-link" })</li>
                            }
                            else if (ac.Role == 1)
                            {
                                <li class="nav-item">@Html.ActionLink("Quản lý cây xanh", "Index", "Greenery", null, new { @class = "nav-link" })</li>
                            }
                            else if (ac.Role == 2)
                            {
                                <li class="nav-item">@Html.ActionLink("Quản lý mua cây xanh", "Index", "Purchase", null, new { @class = "nav-link" })</li>
                            }
                            else if (ac.Role == 3)
                            {
                                <li class="nav-item">@Html.ActionLink("Quản lý phân bón cây xanh", "Index", "Fertilizer", null, new { @class = "nav-link" })</li>
                            }
                            else if (ac.Role == 4)
                            {
                                <li class="nav-item">@Html.ActionLink("Quản lý mua phân bón ", "Index", "BuyF", null, new { @class = "nav-link" })</li>
                            }
                            else if (ac.Role == 5)
                            {
                                <li class="nav-item">@Html.ActionLink("Quản lý cây xanh", "Index", "Greenery", null, new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Quản lý mua cây xanh", "Index", "Purchase", null, new { @class = "nav-link" })</li>
                            }
                            else if (ac.Role == 6)
                            {
                                <li class="nav-item">@Html.ActionLink("Quản lý phân bón cây xanh", "Index", "Fertilizer", null, new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Quản lý mua phân bón ", "Index", "BuyF", null, new { @class = "nav-link" })</li>
                            }

                        }

                    }
                    <li class="nav-item">@Html.ActionLink("Đăng Xuất", "Logout", "Account", null, new { @class = "nav-link" })</li>
                    
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - NHÓM 3</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>