Models/Greenery.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCayXanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Greenery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Greenery()
        {
            this.Buys = new HashSet<Buy>();
        }
    
        public int GreeneryID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Age { get; set; }
        public string Health { get; set; }
        public string Location { get; set; }
        public System.DateTime Createdate { get; set; }
        public string Image { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buys { get; set; }
    }
}

Controllers/GreeneryController.cs
using iTextSharp.text.pdf;
using iTextSharp.text;
using QuanLyCayXanh.Models;
using System;
using System.ComponentModel;
using System.Data.Entity.Validation;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace QuanLyCayXanh.Controllers
{
    public class GreeneryController : Controller
    {
        // GET: Greenery
        QuanLyCayXanhEntities db = new QuanLyCayXanhEntities();

        public ActionResult Index()
        {
            if (Session["TaiKhoan"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View(db.Greeneries.ToList());
        }




        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            Greenery greenery = new Greenery();

            // Kiểm tra trường Name
            if (string.IsNullOrEmpty(f["Name"]))
            {
                ModelState.AddModelError("Name", "Tên không được để trống.");
            }
            else
            {
                greenery.Name = f["Name"];
            }

            // Kiểm tra trường Createdate
            DateTime createdDate;
            string dateString = f["Createdate"];
            if (DateTime.TryParseExact(dateString, "yyyy-MM-dd", null, System.Globalization.DateTimeStyles.None, out createdDate))
            {
                greenery.Createdate = createdDate;
            }
            else
            {
                ModelState.AddModelError("Createdate", "Ngày tạo không hợp lệ. Vui lòng nhập đúng định dạng yyyy-MM-dd.");
            }

            // Kiểm tra trường Age
            int age;
            if (string.IsNullOrEmpty(f["Age"]) || !Int32.TryParse(f["Age"], out age))
            {
                ModelState.AddModelError("Age", "Tuổi không hợp lệ.");
            }
            else
            {
                greenery.Age = age;
            }

            // Kiểm tra trường Type
            if (string.IsNullOrEmpty(f["Type"]))
            {
                ModelState.AddModelError("Type", "Loại không được để trống.");
            }
            else
            {
                greenery.Type = f["Type"];
            }

            // Kiểm tra trường Health
            if (string.IsNullOrEmpty(f["Health"]))
            {
                ModelState.AddModelError("Health", "Tình trạng sức khỏe không được để trống.");
            }
            else
            {
                greenery.Health = f["Health"];
            }

            // Kiểm tra trường Location
            if (string.IsNullOrEmpty(f["Location"]))
            {
                ModelState.AddModelError("Location", "Vị trí không được để trống.");
            }
            else
            {
                greenery.Location = f["Location"];
            }

            // Kiểm tra trường Quantity
            int quantity;
            if (string.IsNullOrEmpty(f["Quantity"]) || !Int32.TryParse(f["Quantity"], out quantity))
            {
                ModelState.AddModelError("Quantity", "Số lượng không hợp lệ.");
            }
            else
            {
                greenery.Quantity = quantity;
            }

            // Kiểm tra trường FileUpload
            if (fFileUpload == null || fFileUpload.ContentLength == 0)
            {
                ModelState.AddModelError("Image", "Hình ảnh không được để trống.");
            }
            else
            {
                var sFileName = Path.GetFileName(fFileUpload.FileName);
                var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                if (!System.IO.File.Exists(path))
                {
                    fFileUpload.SaveAs(path);
                    greenery.Image = sFileName;
                }
                else
                {
                    ModelState.AddModelError("Image", "Hình ảnh đã tồn tại.");
                }
            }

            if (ModelState.IsValid)
            {
                db.Greeneries.Add(greenery);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(greenery);
        }



        public ActionResult Edit(int id)
        {
            var greenery = db.Greeneries.SingleOrDefault(n => n.GreeneryID == id);
            if (greenery == null)
            {
                return HttpNotFound();
            }
            return View(greenery);
        }

        [HttpPost]
        public ActionResult Edit(int id, Greenery model, HttpPostedFileBase fFileUpload)
        {
            var greenery = db.Greeneries.SingleOrDefault(n => n.GreeneryID == id);
            if (greenery == null)
            {
                return HttpNotFound();
            }

            // Kiểm tra và cập nhật trường Name
            if (string.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("Name", "Tên không được để trống.");
            }
            else
            {
                greenery.Name = model.Name;
            }

            // Kiểm tra và cập nhật trường Createdate
            if (model.Createdate == default(DateTime) || model.Createdate > DateTime.Now)
            {
                ModelState.AddModelError("Createdate", "Ngày trồng không hợp lệ. Vui lòng nhập đúng định dạng.");
            }
            else
            {
                greenery.Createdate = model.Createdate;
            }

            // Kiểm tra và cập nhật trường Age
            if (model.Age <= 0)
            {
                ModelState.AddModelError("Age", "Tuổi không hợp lệ. Vui lòng nhập số nguyên lớn hơn 0.");
            }
            else
            {
                greenery.Age = model.Age;
            }

            // Kiểm tra và cập nhật trường Type
            if (string.IsNullOrEmpty(model.Type))
            {
                ModelState.AddModelError("Type", "Loại không được để trống.");
            }
            else
            {
                greenery.Type = model.Type;
            }

            // Kiểm tra và cập nhật trường Health
            if (string.IsNullOrEmpty(model.Health))
            {
                ModelState.AddModelError("Health", "Tình trạng sức khỏe không được để trống.");
            }
            else
            {
                greenery.Health = model.Health;
            }

            // Kiểm tra và cập nhật trường Location
            if (string.IsNullOrEmpty(model.Location))
            {
                ModelState.AddModelError("Location", "Vị trí không được để trống.");
            }
            else
            {
                greenery.Location = model.Location;
            }

            // Kiểm tra và cập nhật trường Quantity
            if (model.Quantity <= 0)
            {
                ModelState.AddModelError("Quantity", "Số lượng không hợp lệ. Vui lòng nhập số nguyên lớn hơn 0.");
            }
            else
            {
                greenery.Quantity = model.Quantity;
            }

            // Xử lý upload file
            if (fFileUpload != null && fFileUpload.ContentLength > 0)
            {
                var fileName = Path.GetFileName(fFileUpload.FileName);
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                fFileUpload.SaveAs(path);
                greenery.Image = fileName;
            }

            // Lưu thay đổi vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    // Xử lý hoặc ghi lại ngoại lệ nếu cần thiết
                    foreach (var error in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in error.ValidationErrors)
                        {
                            ModelState.AddModelError(validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                    return View(greenery); // Trả về view chỉnh sửa với các lỗi xác thực
                }
            }

            return View(greenery); // Trả về view chỉnh sửa với các lỗi xác thực
        }





        public ActionResult Details(int id)
        {
            var greeneryID = db.Greeneries.SingleOrDefault(n => n.GreeneryID == id);
            if (greeneryID == null)
            {
                return HttpNotFound();
            }
            return View(greeneryID);
        }

        public ActionResult Delete(int id)
        {
            var greeneryID = db.Greeneries.SingleOrDefault(n => n.GreeneryID == id);
            if (greeneryID == null)
            {
                return HttpNotFound();
            }
            return View(greeneryID);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var greeneryID = db.Greeneries.SingleOrDefault(n => n.GreeneryID == id);
            if (greeneryID == null)
            {
                return HttpNotFound();
            }
            db.Greeneries.Remove(greeneryID);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Greenery/ExportToPdf
        public ActionResult ExportToPdf()
        {
            var greeneries = db.Greeneries.ToList();

            // Calculate statistics
            int totalCount = greeneries.Count();
            int totalTypesCount = greeneries.Select(g => g.Type).Distinct().Count();
            int totalQuantity = greeneries.Sum(g => g.Quantity ?? 0); // Calculate total quantity of trees

            // Pass data to view
            ViewBag.TotalCount = totalCount;

Views/Greenery/Create.cshtml
@model QuanLyCayXanh.Models.Greenery

@{
    ViewBag.Title = "Tạo Cây Mới";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Thông tin cây xanh</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                @Html.LabelFor(model => model.Name, "Tên cây", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Type, "Loại cây", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Age, "Tuổi cây", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Health, "Tình trạng sức khỏe", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Health, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Health, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-md-2">Ảnh bìa:</label>
                <div class="col-md-10">
                    <input type="file" name="fFileUpload" />
                    @Html.ValidationMessage("Image", "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Location, "Vị trí trồng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Quantity, "Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Createdate, "Ngày trồng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Createdate, new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(model => model.Createdate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="mt-3">
            <input type="submit" value="Tạo mới" class="btn btn-primary" /> |
            @Html.ActionLink("Trở về ", "Index", null, new { @class = "btn btn-outline-dark font-weight-bold ml-2" })
        </div>
    </div>
}

Views/Greenery/Delete.cshtml
@model QuanLyCayXanh.Models.Greenery

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xóa Cây Xanh</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-3">
                Tên cây:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt class="col-sm-3">
                Loại cây:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Type)
            </dd>

            <dt class="col-sm-3">
                Tuổi:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Age)
            </dd>

            <dt class="col-sm-3">
                Tình trạng sức khỏe:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Health)
            </dd>

            <dt class="col-sm-3">
                Vị trí:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Location)
            </dd>

            <dt class="col-sm-3">
                Ngày tạo:
            </dt>
            <dd class="col-sm-9">
                @Model.Createdate.ToString("dd/MM/yyyy")
            </dd>

            <dt class="col-sm-3">
                Số lượng:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Quantity)
            </dd>

            <dt class="col-sm-3">
                Ảnh minh họa:
            </dt>
            <dd class="col-sm-9">
                <img src="~/Images/@Model.Image" class="img-thumbnail" style="max-width: 100px; max-height: 100px;" />
            </dd>
        </dl>


    </div>

</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="mt-3">
        <input type="submit" value="Xóa" class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn xóa cây xanh này không?');" /> |
        @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-secondary" })
    </div>

}

Views/Greenery/Details.cshtml
@model QuanLyCayXanh.Models.Greenery

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin chi tiết cây xanh</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-3">
                Tên cây:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt class="col-sm-3">
                Loại cây:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Type)
            </dd>

            <dt class="col-sm-3">
                Tuổi:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Age)
            </dd>

            <dt class="col-sm-3">
                Tình trạng sức khỏe:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Health)
            </dd>

            <dt class="col-sm-3">
                Vị trí:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Location)
            </dd>

            <dt class="col-sm-3">
                Ngày tạo:
            </dt>
            <dd class="col-sm-9">
                @Model.Createdate.ToString("dd/MM/yyyy")
            </dd>

            <dt class="col-sm-3">
                Số lượng:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Quantity)
            </dd>

            <dt class="col-sm-3">
                Ảnh minh họa:
            </dt>
            <dd class="col-sm-9">
                <img src="~/Images/@Model.Image" class="img-thumbnail" style="max-width: 100px; max-height: 100px;" />
            </dd>
        </dl>
    </div>
</div>

<div class="mt-3">
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.GreeneryID }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-dark" })
</div>

Views/Greenery/Edit.cshtml
@model QuanLyCayXanh.Models.Greenery

@{
    ViewBag.Title = "Chỉnh sửa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-body">
            <h4>Sửa cây xanh</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.GreeneryID)

            <div class="form-group row">
                @Html.LabelFor(model => model.Name, "Tên cây", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Type, "Loại cây", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Age, "Tuổi cây", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Health, "Tình trạng sức khỏe", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Health, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Health, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Location, "Vị trí trồng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Createdate, "Ngày trồng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Createdate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(model => model.Createdate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Quantity, "Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control", type = "number" })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-md-2">
                    Ảnh bìa:
                </label>
                <div class="col-md-10">
                    <input type="file" name="fFileUpload" accept="image/*" />
                    @ViewBag.ThongBao
                </div>
            </div>

        </div>
    </div>
    <div class="mt-3">
        <input type="submit" value="Lưu" class="btn btn-primary" />
        @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-dark ml-2" })
    </div>
}

Views/Greenery/ExportToPdf.cshtml
@model List<QuanLyCayXanh.Models.Greenery>

@{
    ViewBag.Title = "Export to PDF";
    Layout = "~/Views/Shared/_Layout.cshtml";
    // Tính tổng số lượng cây trồng
    int totalQuantity = Model.Sum(g => g.Quantity) ?? 0; // Use ?? operator to handle null case
}
<table class="table table-bordered">
    <thead>
        <form action="@Url.Action("GeneratePdf", "Greenery")" method="post">
            <button type="submit" class="btn btn-primary">Xuất báo cáo PDF</button> |
            @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-dark ml-2" }) @* Quay lại danh sách button *@
        </form>
        <p>
            <strong>Tổng số cây:</strong> @ViewBag.TotalCount<br />
            <strong>Tổng số loại:</strong> @ViewBag.TotalTypesCount<br />
            <strong>Tổng số lượng cây trồng:</strong> @totalQuantity
        </p>
        <tr>
            <th>Tên cây</th>
            <th>Loại cây</th>
            <th>Tuổi</th>
            <th>Sức khỏe</th>
            <th>Vị trí</th>
            <th>Hình ảnh</th>
            <th>Ngày trồng</th>
            <th>Số lượng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var greenery in Model)
        {
            <tr>
                <td>@greenery.Name</td>
                <td>@greenery.Type</td>
                <td>@greenery.Age</td>
                <td>@greenery.Health</td>
                <td>@greenery.Location</td>
                <td>
                    @if (!string.IsNullOrEmpty(greenery.Image))
                    {
                        <img src="@Url.Content("~/Images/" + greenery.Image)" alt="Hình ảnh" style="max-width: 100px; max-height: 100px;" />
                    }
                    else
                    {
                        <span>Không có ảnh</span>
                    }
                </td>
                <td>@greenery.Createdate.ToString("dd-MM-yyyy")</td>
                <td>@greenery.Quantity</td>
            </tr>
        }
    </tbody>
</table>

Views/Greenery/Index.cshtml
@model IEnumerable<QuanLyCayXanh.Models.Greenery>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Quản lý Cây Xanh </h1>
<p>
    @Html.ActionLink("Tạo mới", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Thông kê", "ExportToPdf", null, new { @class = "btn btn-primary" })
</p>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Tên cây</th>
                <th>Loại cây</th>
                <th>Tuổi</th>
                <th>Sức khỏe</th>
                <th>Vị trí</th>
                <th>Hình ảnh</th>
                <th>Ngày trồng</th>
                <th>Số lượng</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Type)</td>
                    <td>@Html.DisplayFor(modelItem => item.Age)</td>
                    <td>@Html.DisplayFor(modelItem => item.Health)</td>
                    <td>@Html.DisplayFor(modelItem => item.Location)</td>
                    <td><img src="~/Images/@item.Image" alt="Hình ảnh" width="50" height="50" /></td>
                    <td>@item.Createdate.ToString("dd-MM-yyyy")</td>
                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                    <td>
                        @Html.ActionLink("Sửa", "Edit", new { id = item.GreeneryID }, new { @class = "btn btn-outline-primary btn-sm mr-1" })
                        @Html.ActionLink("Chi tiết", "Details", new { id = item.GreeneryID }, new { @class = "btn btn-outline-info btn-sm mr-1" })
                        @Html.ActionLink("Xóa", "Delete", new { id = item.GreeneryID }, new { @class = "btn btn-outline-danger btn-sm" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>