Controllers/PurchaseController.cs
using iTextSharp.text.pdf;
using iTextSharp.text;
using QuanLyCayXanh.Models;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyCayXanh.Controllers
{
    public class PurchaseController : Controller
    {
        // GET: Purchase
        QuanLyCayXanhEntities db = new QuanLyCayXanhEntities();

        public ActionResult Index()
        {
            if (Session["TaiKhoan"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View(db.Buys.ToList());
        }

        

        public ActionResult Create()
        {
            ViewBag.GreeneryID = new SelectList(db.Greeneries.ToList().OrderBy(n => n.Name), "GreeneryID", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            if (string.IsNullOrWhiteSpace(f["GreeneryID"]))
            {
                ModelState.AddModelError("GreeneryID", "Không được để trống.");
            }
            if (string.IsNullOrWhiteSpace(f["Provider"]))
            {
                ModelState.AddModelError("Provider", "Không được để trống.");
            }
            if (string.IsNullOrWhiteSpace(f["Quantity"]))
            {
                ModelState.AddModelError("Quantity", "Không được để trống.");
            }
            if (string.IsNullOrWhiteSpace(f["Price"]))
            {
                ModelState.AddModelError("Price", "Không được để trống.");
            }
            if (string.IsNullOrWhiteSpace(f["Date"]))
            {
                ModelState.AddModelError("Date", "Không được để trống.");
            }

            if (!ModelState.IsValid)
            {
                ViewBag.GreeneryID = new SelectList(db.Greeneries.ToList().OrderBy(n => n.Name), "GreeneryID", "Name");
                return View();
            }

            Buy buy = new Buy();
            buy.GreeneryID = int.Parse(f["GreeneryID"]);
            buy.Provider = f["Provider"];
            buy.Quantity = int.Parse(f["Quantity"]);
            buy.Price = int.Parse(f["Price"]);

            DateTime dateValue;
            if (DateTime.TryParseExact(f["Date"], "yyyy-MM-dd", null, System.Globalization.DateTimeStyles.None, out dateValue))
            {
                buy.Date = dateValue;
            }
            else
            {
                ModelState.AddModelError("Date", "Định dạng ngày không hợp lệ (định dạng phải là yyyy-MM-dd).");
                ViewBag.GreeneryID = new SelectList(db.Greeneries.ToList().OrderBy(n => n.Name), "GreeneryID", "Name");
                return View();
            }

            if (fFileUpload != null)
            {
                var sFileName = Path.GetFileName(fFileUpload.FileName);
                var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                if (!System.IO.File.Exists(path))
                {
                    fFileUpload.SaveAs(path);
                }
                buy.Image = sFileName;
            }

            db.Buys.Add(buy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        public ActionResult Edit(int id)
        {
            var buy = db.Buys.SingleOrDefault(n => n.BuyID == id);
            if (buy == null)
            {
                return HttpNotFound();
            }

            ViewBag.GreeneryID = new SelectList(db.Greeneries.ToList().OrderBy(n => n.Name), "GreeneryID", "Name", buy.GreeneryID);
            return View(buy);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Buy model, HttpPostedFileBase fFileUpload)
        {
            // Kiểm tra lỗi xác thực của các trường không được để trống
            if (model.GreeneryID == 0)
            {
                ModelState.AddModelError("GreeneryID", "Tên cây xanh không được để trống.");
            }
            if (string.IsNullOrWhiteSpace(model.Provider))
            {
                ModelState.AddModelError("Provider", "Nhà cung cấp không được để trống.");
            }
            if (model.Quantity <= 0)
            {
                ModelState.AddModelError("Quantity", "Số lượng phải lớn hơn 0.");
            }
            if (model.Price <= 0)
            {
                ModelState.AddModelError("Price", "Giá tiền phải lớn hơn 0.");
            }
            if (model.Date == DateTime.MinValue)
            {
                ModelState.AddModelError("Date", "Ngày mua không được để trống.");
            }

            // Nếu có lỗi, trở về view với thông báo lỗi
            if (!ModelState.IsValid)
            {
                ViewBag.GreeneryID = new SelectList(db.Greeneries.ToList().OrderBy(n => n.Name), "GreeneryID", "Name", model.GreeneryID);
                return View(model);
            }

            var buy = db.Buys.SingleOrDefault(n => n.BuyID == model.BuyID);
            if (buy == null)
            {
                return HttpNotFound();
            }

            // Cập nhật thông tin từ form
            buy.GreeneryID = model.GreeneryID;
            buy.Provider = model.Provider;
            buy.Quantity = model.Quantity;
            buy.Date = model.Date;
            buy.Price = model.Price;

            // Kiểm tra và xử lý file upload
            if (fFileUpload != null && fFileUpload.ContentLength > 0)
            {
                var sFileName = Path.GetFileName(fFileUpload.FileName);
                var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                if (!System.IO.File.Exists(path))
                {
                    fFileUpload.SaveAs(path);
                }
                buy.Image = sFileName;
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }








        public ActionResult Details(int id)
        {
            var buy = db.Buys.SingleOrDefault(n => n.BuyID == id);
            if (buy == null)
            {
                return HttpNotFound();
            }
            return View(buy);
        }

        public ActionResult Delete(int id)
        {
            var buy = db.Buys.SingleOrDefault(n => n.BuyID == id);
            if (buy == null)
            {
                return HttpNotFound();
            }
            return View(buy);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var buy = db.Buys.SingleOrDefault(n => n.BuyID == id);
            if (buy == null)
            {
                return HttpNotFound();
            }
            db.Buys.Remove(buy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        
        public ActionResult ExportToPdf()
        {
            var purchases = db.Buys.ToList();

            // Calculate statistics
            int totalPurchases = purchases.Count();
            int totalProviders = purchases.Select(p => p.Provider).Distinct().Count();
            int totalTypes = purchases.Select(p => p.GreeneryID).Distinct().Count(); // Assume GreeneryID represents the type of greenery
            int totalQuantity = purchases.Sum(p => p.Quantity);
            int totalPrice = purchases.Sum(p => p.Price);

            // Pass data to view
            ViewBag.TotalCount = totalPurchases;
            ViewBag.TotalProviders = totalProviders;
            ViewBag.TotalTypes = totalTypes;
            ViewBag.TotalQuantity = totalQuantity;
            ViewBag.TotalPrice = totalPrice;

            return View(purchases);
        }


        // POST: Purchase/GeneratePdf
        [HttpPost]
        public ActionResult GeneratePdf()
        {
            var purchases = db.Buys.ToList();

            int totalTypes = purchases.Select(p => p.GreeneryID).Distinct().Count(); // Assume GreeneryID represents the type of greenery
            int totalQuantity = purchases.Sum(p => p.Quantity);
            decimal totalPrice = purchases.Sum(b => b.Price * b.Quantity);

            // MemoryStream to hold the generated PDF
            MemoryStream workStream = new MemoryStream();

            // Create a new PDF document
            Document document = new Document(PageSize.A4, 25, 25, 30, 30);

            // Initialize PDF writer and bind it to the MemoryStream
            PdfWriter.GetInstance(document, workStream).CloseStream = false;

            // Open the document
            document.Open();

            // Set the time zone to Vietnam
            TimeZoneInfo vietnamTimeZone = TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time");
            DateTime vietnamTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, vietnamTimeZone);

            // Add title
            string title = "Báo Cáo Cây Xanh";
            string reportDate = vietnamTime.ToString("dd/MM/yyyy");

            // Output the report date
            Console.WriteLine(reportDate);

            // Đường dẫn tương đối đến font
            string fontPath = Server.MapPath("~/Fonts/times.ttf");

            // Tạo BaseFont từ font đã cài đặt
            BaseFont baseFont = BaseFont.CreateFont(fontPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);

            // Tạo một Font sử dụng BaseFont đã tạo
            Font font = new Font(baseFont, 12, Font.NORMAL);

            // Add title using the specified font
            document.Add(new Paragraph(title, font));

            // Add report date
            document.Add(new Paragraph("Ngày xuất báo cáo: " + reportDate, font));

            // Add statistics
            document.Add(new Paragraph("\n"));
            document.Add(new Paragraph("Tổng loại cây: " + totalTypes, font));
            document.Add(new Paragraph("Tổng số lượng: " + totalQuantity, font));
            document.Add(new Paragraph("Tổng giá trị phân bón: " + totalPrice.ToString("N0") + " ₫", font)); // Thay đổi định dạng giá

Views/Purchase/Create.cshtml
@model QuanLyCayXanh.Models.Buy

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Purchase", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-body">
            <h4>Mua Cây Xanh</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
            @Html.LabelFor(model => model.GreeneryID, "Tên Cây Xanh: ")

            <div class="col-md-10">
                @Html.DropDownList("GreeneryID")
            </div>
        </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Provider, "Nhà Cung Cấp:")

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Provider, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Provider, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, "Số lượng:")

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            @*            <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>*@
            <div class="form-group">
                @Html.LabelFor(model => model.Date, "Ngày: ")
                @Html.TextBoxFor(model => model.Date, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Date, "Giá tiền:")

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Ảnh bìa:
                </label>
                <div class="col-md-10">
                    <input type="file" name="fFileUpload" />
                    @ViewBag.ThongBao
                </div>
            </div>
        </div>
    </div>
    <div class="mt-3">

        <input type="submit" value="Tạo mới" class="btn btn-primary" /> |
        @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-dark font-weight-bold ml-2" })

    </div>
}

Views/Purchase/Delete.cshtml
@model QuanLyCayXanh.Models.Buy

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xóa Cây Xanh</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-3">
                Tên cây:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Greenery.Name)
            </dd>

            <dt class="col-sm-3">
                Nhà cung cấp:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Provider)
            </dd>

            <dt class="col-sm-3">
                Số lượng:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Quantity)
            </dd>

            <dt class="col-sm-3">
                Ngày:
            </dt>
            <dd class="col-sm-9">
                @Model.Date.ToString("dd/MM/yyyy")
            </dd>

            <dt class="col-sm-3">
                Giá tiền:
            </dt>
            <dd class="col-sm-9">
                @(Model.Price.ToString("N0") + " ₫")
            </dd>

            <dt class="col-sm-3">
                Ảnh minh họa:
            </dt>
            <dd class="col-sm-9">
                <img src="~/Images/@Model.Image" class="img-thumbnail" style="max-width: 100px; max-height: 100px;" />
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="mt-3">
                <input type="submit" value="Xóa" class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn xóa cây xanh này không?');" /> |
                @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        }
    </div>
</div>

Views/Purchase/Details.cshtml
@model QuanLyCayXanh.Models.Buy

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin chi tiết mua cây xanh</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-3">
                Mã cây xanh:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.GreeneryID)
            </dd>

            <dt class="col-sm-3">
                Nhà cung cấp:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Provider)
            </dd>

            <dt class="col-sm-3">
                Số lượng:
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Quantity)
            </dd>

            <dt class="col-sm-3">
                Ngày mua:
            </dt>
            <dd class="col-sm-9">
                @Model.Date.ToString("dd/MM/yyyy")
            </dd>

            <dt class="col-sm-3">
                Giá:
            </dt>
            <dd class="col-sm-9">
                @(Model.Price.ToString("N0") + " ₫")
            </dd>

            <dt class="col-sm-3">
                Ảnh minh họa:
            </dt>
            <dd class="col-sm-9">
                <img src="~/Images/@Model.Image" class="img-thumbnail" style="max-width: 100px; max-height: 100px;" />
            </dd>
        </dl>   
    </div>
</div>
<div class="mt-3">
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.BuyID }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-dark" })
</div>

Views/Purchase/Edit.cshtml
@model QuanLyCayXanh.Models.Buy

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Purchase", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-body">
            <h4>Sửa Mua Cây Xanh</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.BuyID)

            <div class="form-group">
                @Html.LabelFor(model => model.GreeneryID, "Tên Cây Xanh: ")
                <div class="col-md-10">
                    @Html.DropDownList("GreeneryID", ViewBag.GreeneryID as SelectList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.GreeneryID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Provider, "Nhà Cung Cấp: ")
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Provider, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Provider, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, "Số Lượng: ")
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, "Ngày Mua: ", htmlAttributes: new { @class = "control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Date, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, "Giá Tiền")
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">Ảnh bìa:</label>
                <div class="col-md-10">
                    <input type="file" name="fFileUpload" />
                    @ViewBag.ThongBao
                </div>
            </div>
        </div>
    </div>

    <div class="mt-3">
        <input type="submit" value="Lưu" class="btn btn-primary" />
        @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-dark ml-2" })
    </div>
}

Views/Purchase/ExportToPdf.cshtml
@model List<QuanLyCayXanh.Models.Buy>

@{
    ViewBag.Title = "Export to PDF";
    Layout = "~/Views/Shared/_Layout.cshtml";

    // Tính tổng giá trị phân bón
    decimal totalPrice = Model.Sum(b => b.Price * b.Quantity);
}
<form action="@Url.Action("GeneratePdf", "Purchase")" method="post">
    <button type="submit" class="btn btn-primary">Xuất báo cáo PDF</button> |
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-dark ml-2" })
</form>

<p>
    <strong>Tổng loại cây:</strong> @ViewBag.TotalTypes<br />
    <strong>Tổng số lượng:</strong> @ViewBag.TotalQuantity<br />
    <strong>Tổng giá trị cây xanh:</strong> @String.Format("{0:0,0} ₫", totalPrice)
</p>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Tên Cây Xanh</th>
            <th>Số lượng</th>
            <th>Nhà cung cấp</th>
            <th>Ngày mua</th>
            <th>Giá tiền</th>
            <th>Hình Ảnh</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var buy in Model)
        {
            <tr>
                <td>@buy.Greenery.Name</td>
                <td>@buy.Quantity</td>
                <td>@buy.Provider</td>
                <td>@buy.Date.ToString("dd-MM-yyyy")</td>
                <td>@(buy.Price.ToString("N0") + " ₫")</td>
                <td>
                    @if (!string.IsNullOrEmpty(buy.Image))
                    {
                        <img src="@Url.Content("~/Images/" + buy.Image)" alt="Purchase Image" style="max-width: 80px; max-height: 80px;" />
                    }
                    else
                    {
                        <span>Không có ảnh</span>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Purchase/Index.cshtml
@model IEnumerable<QuanLyCayXanh.Models.Buy>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Quản Lý Mua Cây Xanh </h1>
<p>
    @Html.ActionLink("Tạo mới", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Thông kê", "ExportToPdf", null, new { @class = "btn btn-primary" })
</p>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Tên Cây Xanh</th>
                <th>Số lượng</th>
                <th>Nhà cung cấp</th>
                <th>Ngày mua</th>
                <th>Giá tiền</th>
                <th>Hình Ảnh</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Greenery.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                    <td>@Html.DisplayFor(modelItem => item.Provider)</td>
                    <td>@item.Date.ToString("dd/MM/yyyy")</td>
                    <td>
                        @((item.Price * item.Quantity).ToString("N0") + " ₫")
                    </td>
                    <td>

                        <img src="~/Images/@item.Image" alt="Hình ảnh" width="50" height="50" />
                    </td>
                    <td width="180">
                        @Html.ActionLink("Sửa", "Edit", new { id = item.BuyID }, new { @class = "btn btn-outline-primary btn-sm mr-1" })
                        @Html.ActionLink("Chi tiết", "Details", new { id = item.BuyID }, new { @class = "btn btn-outline-info btn-sm mr-1" })
                        @Html.ActionLink("Xóa", "Delete", new { id = item.BuyID }, new { @class = "btn btn-outline-danger btn-sm" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>